[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  branches = ['main']
  customDomain = "stfranciscus-heverlee.org"
  renderJavaScript = true
package = "netlify-plugin-submit-sitemap"

	[plugins.inputs]

	# The base url of your site (optional, default = main URL set in Netlify)
	baseUrl = "stfranciscus-heverlee.org"

	# Path to the sitemap URL (optional, default = /sitemap.xml)
	sitemapPath = "/sitemap.xml"

	# Time in seconds to not submit the sitemap after successful submission
	ignorePeriod = 0

	# Enabled providers to submit sitemap to (optional, default = 'google', 'yandex'). Possible providers are currently only 'google', 'yandex'.
	providers = [
		"google",
		"yandex"
	]
package = "@netlify/plugin-sitemap"

  [plugins.inputs]
  baseUrl = "https://stfranciscus-heverlee.org"